app.environment=dev





# EMAIL GMAIL
#Gmail, per modificare la password andare a https://myaccount.google.com/security e poi alla pagina https://security.google.com/settings/security/apppasswords
# mail.default.from=LunaSapiens <info@lunasapiens.com> # vanno nello spam se invii email con questo from. Perché in realtà la email è gmail.com
gmail.mail.username=matteo.manili@gmail.com 
gmail.mail.password=${GMAIL_MAIL_PASSWORD} 
gmail.mail.smtp.host=smtp.gmail.com
gmail.mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.debug=false