app.environment=prod





# AMAZON SES SMTP SETTING: https://eu-central-1.console.aws.amazon.com/ses/home (Nome utente IAM: ses-smtp-lunasapiens)
mail.username=AKIA2TPRSNOZX7VBGWQY
mail.password=${MAIL_PASSWORD}
mail.smtp.host=email-smtp.eu-central-1.amazonaws.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.debug=false